/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicContactsRouteImport } from './routes/_public/contacts'
import { Route as AdminNewsRouteRouteImport } from './routes/admin/news/route'
import { Route as AdminCustomerRequestsRouteRouteImport } from './routes/admin/customer-requests/route'
import { Route as AdminBannersRouteRouteImport } from './routes/admin/banners/route'
import { Route as AuthSignInIndexRouteImport } from './routes/auth/sign-in/index'
import { Route as AdminNewsIndexRouteImport } from './routes/admin/news/index'
import { Route as AdminCustomerRequestsIndexRouteImport } from './routes/admin/customer-requests/index'
import { Route as AdminBannersIndexRouteImport } from './routes/admin/banners/index'
import { Route as PublicNewsIndexRouteImport } from './routes/_public/news/index'
import { Route as PublicCalculatorIndexRouteImport } from './routes/_public/calculator/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as PublicNewsSlugRouteImport } from './routes/_public/news/$slug'
import { Route as PublicProductsCategoryIndexRouteImport } from './routes/_public/products/$category/index'
import { Route as AdminNewsIdEditRouteImport } from './routes/admin/news/$id/edit'
import { Route as AdminBannersIdEditRouteImport } from './routes/admin/banners/$id/edit'
import { Route as PublicProductsCategorySubcategoryRouteImport } from './routes/_public/products/$category/$subcategory'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicContactsRoute = PublicContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminNewsRouteRoute = AdminNewsRouteRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomerRequestsRouteRoute =
  AdminCustomerRequestsRouteRouteImport.update({
    id: '/customer-requests',
    path: '/customer-requests',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminBannersRouteRoute = AdminBannersRouteRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/auth/sign-in/',
  path: '/auth/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsIndexRoute = AdminNewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminNewsRouteRoute,
} as any)
const AdminCustomerRequestsIndexRoute =
  AdminCustomerRequestsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminCustomerRequestsRouteRoute,
  } as any)
const AdminBannersIndexRoute = AdminBannersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBannersRouteRoute,
} as any)
const PublicNewsIndexRoute = PublicNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicCalculatorIndexRoute = PublicCalculatorIndexRouteImport.update({
  id: '/calculator/',
  path: '/calculator/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicNewsSlugRoute = PublicNewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicProductsCategoryIndexRoute =
  PublicProductsCategoryIndexRouteImport.update({
    id: '/products/$category/',
    path: '/products/$category/',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const AdminNewsIdEditRoute = AdminNewsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminNewsRouteRoute,
} as any)
const AdminBannersIdEditRoute = AdminBannersIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminBannersRouteRoute,
} as any)
const PublicProductsCategorySubcategoryRoute =
  PublicProductsCategorySubcategoryRouteImport.update({
    id: '/products/$category/$subcategory',
    path: '/products/$category/$subcategory',
    getParentRoute: () => PublicRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/banners': typeof AdminBannersRouteRouteWithChildren
  '/admin/customer-requests': typeof AdminCustomerRequestsRouteRouteWithChildren
  '/admin/news': typeof AdminNewsRouteRouteWithChildren
  '/contacts': typeof PublicContactsRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/news/$slug': typeof PublicNewsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/calculator/': typeof PublicCalculatorIndexRoute
  '/news/': typeof PublicNewsIndexRoute
  '/admin/banners/': typeof AdminBannersIndexRoute
  '/admin/customer-requests/': typeof AdminCustomerRequestsIndexRoute
  '/admin/news/': typeof AdminNewsIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/products/$category/$subcategory': typeof PublicProductsCategorySubcategoryRoute
  '/admin/banners/$id/edit': typeof AdminBannersIdEditRoute
  '/admin/news/$id/edit': typeof AdminNewsIdEditRoute
  '/products/$category/': typeof PublicProductsCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/contacts': typeof PublicContactsRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/news/$slug': typeof PublicNewsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/calculator': typeof PublicCalculatorIndexRoute
  '/news': typeof PublicNewsIndexRoute
  '/admin/banners': typeof AdminBannersIndexRoute
  '/admin/customer-requests': typeof AdminCustomerRequestsIndexRoute
  '/admin/news': typeof AdminNewsIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/products/$category/$subcategory': typeof PublicProductsCategorySubcategoryRoute
  '/admin/banners/$id/edit': typeof AdminBannersIdEditRoute
  '/admin/news/$id/edit': typeof AdminNewsIdEditRoute
  '/products/$category': typeof PublicProductsCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/banners': typeof AdminBannersRouteRouteWithChildren
  '/admin/customer-requests': typeof AdminCustomerRequestsRouteRouteWithChildren
  '/admin/news': typeof AdminNewsRouteRouteWithChildren
  '/_public/contacts': typeof PublicContactsRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_public/news/$slug': typeof PublicNewsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_public/calculator/': typeof PublicCalculatorIndexRoute
  '/_public/news/': typeof PublicNewsIndexRoute
  '/admin/banners/': typeof AdminBannersIndexRoute
  '/admin/customer-requests/': typeof AdminCustomerRequestsIndexRoute
  '/admin/news/': typeof AdminNewsIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/_public/products/$category/$subcategory': typeof PublicProductsCategorySubcategoryRoute
  '/admin/banners/$id/edit': typeof AdminBannersIdEditRoute
  '/admin/news/$id/edit': typeof AdminNewsIdEditRoute
  '/_public/products/$category/': typeof PublicProductsCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/banners'
    | '/admin/customer-requests'
    | '/admin/news'
    | '/contacts'
    | '/admin/'
    | '/auth/'
    | '/news/$slug'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/calculator/'
    | '/news/'
    | '/admin/banners/'
    | '/admin/customer-requests/'
    | '/admin/news/'
    | '/auth/sign-in/'
    | '/products/$category/$subcategory'
    | '/admin/banners/$id/edit'
    | '/admin/news/$id/edit'
    | '/products/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/contacts'
    | '/'
    | '/admin'
    | '/auth'
    | '/news/$slug'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/calculator'
    | '/news'
    | '/admin/banners'
    | '/admin/customer-requests'
    | '/admin/news'
    | '/auth/sign-in'
    | '/products/$category/$subcategory'
    | '/admin/banners/$id/edit'
    | '/admin/news/$id/edit'
    | '/products/$category'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/admin/banners'
    | '/admin/customer-requests'
    | '/admin/news'
    | '/_public/contacts'
    | '/_public/'
    | '/admin/'
    | '/auth/'
    | '/_public/news/$slug'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/_public/calculator/'
    | '/_public/news/'
    | '/admin/banners/'
    | '/admin/customer-requests/'
    | '/admin/news/'
    | '/auth/sign-in/'
    | '/_public/products/$category/$subcategory'
    | '/admin/banners/$id/edit'
    | '/admin/news/$id/edit'
    | '/_public/products/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/contacts': {
      id: '/_public/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof PublicContactsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customer-requests': {
      id: '/admin/customer-requests'
      path: '/customer-requests'
      fullPath: '/admin/customer-requests'
      preLoaderRoute: typeof AdminCustomerRequestsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/news/': {
      id: '/admin/news/'
      path: '/'
      fullPath: '/admin/news/'
      preLoaderRoute: typeof AdminNewsIndexRouteImport
      parentRoute: typeof AdminNewsRouteRoute
    }
    '/admin/customer-requests/': {
      id: '/admin/customer-requests/'
      path: '/'
      fullPath: '/admin/customer-requests/'
      preLoaderRoute: typeof AdminCustomerRequestsIndexRouteImport
      parentRoute: typeof AdminCustomerRequestsRouteRoute
    }
    '/admin/banners/': {
      id: '/admin/banners/'
      path: '/'
      fullPath: '/admin/banners/'
      preLoaderRoute: typeof AdminBannersIndexRouteImport
      parentRoute: typeof AdminBannersRouteRoute
    }
    '/_public/news/': {
      id: '/_public/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof PublicNewsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/calculator/': {
      id: '/_public/calculator/'
      path: '/calculator'
      fullPath: '/calculator/'
      preLoaderRoute: typeof PublicCalculatorIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/news/$slug': {
      id: '/_public/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof PublicNewsSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/products/$category/': {
      id: '/_public/products/$category/'
      path: '/products/$category'
      fullPath: '/products/$category/'
      preLoaderRoute: typeof PublicProductsCategoryIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/news/$id/edit': {
      id: '/admin/news/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/news/$id/edit'
      preLoaderRoute: typeof AdminNewsIdEditRouteImport
      parentRoute: typeof AdminNewsRouteRoute
    }
    '/admin/banners/$id/edit': {
      id: '/admin/banners/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/banners/$id/edit'
      preLoaderRoute: typeof AdminBannersIdEditRouteImport
      parentRoute: typeof AdminBannersRouteRoute
    }
    '/_public/products/$category/$subcategory': {
      id: '/_public/products/$category/$subcategory'
      path: '/products/$category/$subcategory'
      fullPath: '/products/$category/$subcategory'
      preLoaderRoute: typeof PublicProductsCategorySubcategoryRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicContactsRoute: typeof PublicContactsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicNewsSlugRoute: typeof PublicNewsSlugRoute
  PublicCalculatorIndexRoute: typeof PublicCalculatorIndexRoute
  PublicNewsIndexRoute: typeof PublicNewsIndexRoute
  PublicProductsCategorySubcategoryRoute: typeof PublicProductsCategorySubcategoryRoute
  PublicProductsCategoryIndexRoute: typeof PublicProductsCategoryIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicContactsRoute: PublicContactsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicNewsSlugRoute: PublicNewsSlugRoute,
  PublicCalculatorIndexRoute: PublicCalculatorIndexRoute,
  PublicNewsIndexRoute: PublicNewsIndexRoute,
  PublicProductsCategorySubcategoryRoute:
    PublicProductsCategorySubcategoryRoute,
  PublicProductsCategoryIndexRoute: PublicProductsCategoryIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AdminBannersRouteRouteChildren {
  AdminBannersIndexRoute: typeof AdminBannersIndexRoute
  AdminBannersIdEditRoute: typeof AdminBannersIdEditRoute
}

const AdminBannersRouteRouteChildren: AdminBannersRouteRouteChildren = {
  AdminBannersIndexRoute: AdminBannersIndexRoute,
  AdminBannersIdEditRoute: AdminBannersIdEditRoute,
}

const AdminBannersRouteRouteWithChildren =
  AdminBannersRouteRoute._addFileChildren(AdminBannersRouteRouteChildren)

interface AdminCustomerRequestsRouteRouteChildren {
  AdminCustomerRequestsIndexRoute: typeof AdminCustomerRequestsIndexRoute
}

const AdminCustomerRequestsRouteRouteChildren: AdminCustomerRequestsRouteRouteChildren =
  {
    AdminCustomerRequestsIndexRoute: AdminCustomerRequestsIndexRoute,
  }

const AdminCustomerRequestsRouteRouteWithChildren =
  AdminCustomerRequestsRouteRoute._addFileChildren(
    AdminCustomerRequestsRouteRouteChildren,
  )

interface AdminNewsRouteRouteChildren {
  AdminNewsIndexRoute: typeof AdminNewsIndexRoute
  AdminNewsIdEditRoute: typeof AdminNewsIdEditRoute
}

const AdminNewsRouteRouteChildren: AdminNewsRouteRouteChildren = {
  AdminNewsIndexRoute: AdminNewsIndexRoute,
  AdminNewsIdEditRoute: AdminNewsIdEditRoute,
}

const AdminNewsRouteRouteWithChildren = AdminNewsRouteRoute._addFileChildren(
  AdminNewsRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminBannersRouteRoute: typeof AdminBannersRouteRouteWithChildren
  AdminCustomerRequestsRouteRoute: typeof AdminCustomerRequestsRouteRouteWithChildren
  AdminNewsRouteRoute: typeof AdminNewsRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBannersRouteRoute: AdminBannersRouteRouteWithChildren,
  AdminCustomerRequestsRouteRoute: AdminCustomerRequestsRouteRouteWithChildren,
  AdminNewsRouteRoute: AdminNewsRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
